### PR TITLE
Rename "outer product" to "cross product"

### PR DESCRIPTION
**Pull request by impiaaa**
Add a note to mention the old name

### CODE REVIEW

**Comment by nicolasnoble** [comment]
A bit of a nit, but, sure.

**Comment by impiaaa** [comment]
> A bit of a nit, but, sure.

It's confused me more than once. Wikipedia says the "outer product" is a totally different operation.

**Comment by nicolasnoble** [comment]
Eh? Where does it say that? The outer product is a specialization of the cross product, really.

**Comment by impiaaa** [comment]
They define the [outer product](https://en.wikipedia.org/wiki/Outer_product) as a multiplication of two vectors, sized *m* and *n*, resulting in an *m*×*n* matrix; and the [cross product](https://en.wikipedia.org/wiki/Cross_product) as a multiplication of two vectors of equal size, resulting in a vector also of equal size. If the two operations are related, it's not discussed on either page. And FWIW, I've only ever heard the term "cross product" in computer graphics contexts, never "outer product" (except here).

**Pull request merged**
